### ISSUE TITLE
Change references to linkeddata.github.com

### ISSUE THREAD

**Issue by kirkhess** [linkeddata/tabulator-chrome#4]
skin.html refers to:
https://w3.scripts.mit.edu/tabulator/js/mashup/mashlib.js
which I assume is also this file:
https://github.com/linkeddata/tabulator/blob/master/js/mashup/mashlib.js

The first statement refers to a non-existent url & the iconPrefix needs to be fixed as well.

``` javascript
tabulator.scriptBase = 'https://linkeddata.github.com/tabulator/'; // This no longer works.

tabulator.iconPrefix = tabulator.scriptBase; //this also needs to be fixed
```

See also: linkeddata/tabulator#6

**Comment by timbl** [comment]
This is a bug in tabulator just fixed in https://github.com/linkeddata/tabulator/commit/06cf49bf287d7c35b338ec11e0edd5f3c43e0774
